### ISSUE TITLE
Purpose of `hold_start` in `KeyState`

### ISSUE THREAD

**Issue by lonesometraveler** [HaoboGu/rmk#12]
A question about `KeyState`'s `hold_start`.

```rust
pub(crate) struct KeyState {
    pub(crate) pressed: bool,
    pub(crate) changed: bool,
    hold_start: Option<Instant>,
}
```
`Matrix` has this function:

```rust
pub(crate) fn key_pressed(&mut self, row: usize, col: usize) {
    // COL2ROW
    #[cfg(feature = "col2row")]
    self.key_states[col][row].start_timer();

    // ROW2COL
    #[cfg(not(feature = "col2row"))]
    self.key_states[row][col].start_timer();
}
```
And `Keyboard` calls it to start a timer at this line:
https://github.com/HaoboGu/rmk/blob/766eb21b57d1850397428d11bdc16fb4a7849def/rmk/src/keyboard.rs#L242

However, it seems that the timer is not cleared or referenced in the current implementation. So, the `hold_start` field is effectively unused. What is the purpose of `hold_start`?

**Comment by HaoboGu** [comment]
Yes, it's not used for now. This timer will be used in tap_hold feature, which haven't implemented yet.
