### ISSUE TITLE
1 random key won't work after PC resumed from sleep

### ISSUE THREAD

**Issue by mangkoran** [HaoboGu/rmk#135]
This might be a bit hard to troubleshoot or reproduce. Somehow after I resumed my PC from sleep, one random key on my keyboard seems not working. First I noticed it was the "0" key, and the next time it was the "S" key, and the next time it was the "0" key. I need to unplug and replug it to make it work again. Please let me know if you need something to help with this issue.

Config could be found here https://github.com/HaoboGu/rmk/issues/130#issue-2645999151

Pro Micro RP2040 (16M flash)
rmk v0.4.1

**Comment by HaoboGu** [comment]
Could you post your `Cargo.toml` here? 

It's quite weird since only one key doesn't work. Does this behavior happen only for some specific keys? I have no idea now.. 🥲

**Comment by HaoboGu** [comment]
Could you try to increase the default storage size used for storing keymaps? aka setting the `num_sectors` to 8 or 16:

https://haobogu.github.io/rmk/keyboard_configuration.html#storage

**Comment by mangkoran** [comment]
I have increase the `num_sectors` to 16 and seems it's fixed now. Thank you!

Anyway, how do I know how many sectors my flash is? The tech spec is [here](https://www.mouser.com/datasheet/2/949/w25q128jv_revf_03272018_plus-1489608.pdf) but I couldn't find any mention regarding sector count.

**Comment by HaoboGu** [comment]
@mangkoran You have a 4K sector size, and 128M-bit(16M byte) in total, so the total number of sectors is 16M/4K = 4K. Plenty much that you can use :D
