### ISSUE TITLE
A new real world example

### ISSUE THREAD

**Issue by lqlklu** [HaoboGu/rmk#136]
I created a new real world example. May I add it to Real World Example of docs?
It is tested working well with rmk and easy to fork.
GitHub Project: [https://github.com/lqlklu/ergox-keyboard](https://github.com/lqlklu/ergox-keyboard)
JLC Project: [https://oshwhub.com/lqlklu/ergox](https://oshwhub.com/lqlklu/ergox)

**Comment by lqlklu** [comment]
Thank you so much.

**Comment by HaoboGu** [comment]
I'm closing this, you can just open a PR to add your keyboard 😄
