### ISSUE TITLE
Add an option making it possible to update keymap when re-flashing

### ISSUE THREAD

**Issue by HaoboGu** [HaoboGu/rmk#156]

**Comment by mangkoran** [comment]
Is this ticket similar to https://github.com/HaoboGu/rmk/issues/130 ?

**Comment by HaoboGu** [comment]
> Is this ticket similar to #130 ?

Yes, but when enabling `clear_storage` option, the storage would be erased on every reboot. It can only be used for testing situation

**Comment by HaoboGu** [comment]
> If so, could we have another config where we could clear the storage during firmware flash only? So we could have two different config for two different purpose.

I think it's impossible. The firmware doesn't know this.

**Comment by HaoboGu** [comment]
zmk does it by having a separate firmware `reset-config`. If you want to clear the storage, you have to flash the `reset-config` firmware first, then flash the keyboard firmware

**Comment by mangkoran** [comment]
> I think it's impossible. The firmware has no way to know whether current boot is right after a re-flashing

You are correct. At first I thought it's possible to implement in flasher/CLI, but then I forgot that I use UF2 bootloader to flash the firmware. Thank you for answering my question. I've been using RMK ever since I found it <3
