### ISSUE TITLE
keymap not effected

### ISSUE THREAD

**Issue by jsenjobs** [HaoboGu/rmk#166]
**mcu:** 
nrf52840

**bootloader & sd:**
UF2 Bootloader 0.8.0-2-g6a2493b lib/nrfx (v2.0.0) lib/tinyusb (0.12.0-145-g9775e7691) lib/uf2 (remotes/origin/configupdate-9-gadbb8c7)
Model: QHKB
Board-ID: QHKB
Date: Feb 25 2024
SoftDevice: S140 7.2.0

**use example:**
/examples/use_config/nrf52840_ble_split
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/2b36c3a7-14c9-47db-8bfd-d6cf14d56997">

**change input & output pins:**
<img width="556" alt="image" src="https://github.com/user-attachments/assets/7f7ca6cf-31b1-4ad8-b0a3-2ac6cc1fdd81">

It seems that the keymap configuration has not taken effect, and all the keys only output 1.
<img width="856" alt="image" src="https://github.com/user-attachments/assets/83faae09-f237-422a-96e8-db4a8ea04b10">

Also tried 
`[storage]
clear_storage = true`
, but it still didn't work.

**Comment by pcasotti** [comment]
Have you tried running `cargo clean`?

**Comment by jsenjobs** [comment]
> Have you tried running `cargo clean`?

tried ~

**Comment by HaoboGu** [comment]
can you change your keymap using vial？

**Comment by HaoboGu** [comment]
Any updates?

**Comment by jsenjobs** [comment]
> Any updates?

The keymap is fine now. After I used fix/lag and returned to main, code were no changes. I will continue testing. Additionally, on Mac, the Bluetooth may become unable to connect after a while, requiring the deletion of Bluetooth devices and reconnection. I will check this in detail in my future tests. 

thanks.
