### ISSUE TITLE
Vial not working with BLE

### ISSUE THREAD

**Issue by thomasaarholt** [HaoboGu/rmk#182]
I've just got my BLE keyboard working with rmk 0.4.4 (hooray!), but when I try to use vial to adjust the keymap, I get this error:

<img width="532" alt="image" src="https://github.com/user-attachments/assets/80b54622-cc54-448b-97d1-0b556569dc4b" />

It still works with USB, so it isn't a problem for me, but it might be nice to add to the docs if this is intentional / only USB is supported for vial realtime updates.

**Comment by HaoboGu** [comment]
It's a known issue. vial over BLE does work, but very unstable. It seems that it's affected by the network environment, signal strength, etc.

I would recommend to use USB when updating keymap for now

**Comment by thomasaarholt** [comment]
That makes sense! 

I hope you don’t mind me making all these issues! I am REALLY enjoying working with rmk, and I am so satisfied with making my own keyboard.

**Comment by HaoboGu** [comment]
Not at all! I'm happy to hear feedback from users, whether it’s positive or negative :D

**Comment by thomasaarholt** [comment]
I managed to get this [branch/PR of vial](https://github.com/vial-kb/vial-gui/pull/238) working (with quite a bit of trouble), and it works well with bluetooth :)

**Comment by HaoboGu** [comment]
Interesting, I don't see anything changed that would fix the BLE connection failure. Any ideas?

**Comment by thomasaarholt** [comment]
No. I was thinking initially that updating vial from Python 3.6 to anything else was bound to bring a lot of under-the-hood improvements, but there wasn't really anything standing out massively. But I haven't tested a lot.
