### ISSUE TITLE
Registered keycodes cannot unregister properly

### ISSUE THREAD

**Issue by drindr** [HaoboGu/rmk#210]
When I type extremely fast (randomly type. xD), some keycodes may be left in the `KeyboardReport.keycodes`, then the keyboard crash after a while.
I can stable reproduce this issue with `ModifierTapHold`.
Seems like a data racing problem? I am not sure about it.

**Comment by HaoboGu** [comment]
Might be a bug in tap-hold implementation? I tested on my keyboard(split without tap hold key), I cannot reproduce it.

**Comment by drindr** [comment]
fixed by  #212
