### ISSUE TITLE
Board: Support for `ESP32-S3`

### ISSUE THREAD

**Issue by mbana** [HaoboGu/rmk#23]
Hi,

Any plans to support this board?

* https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html
* https://www.espressif.com/en/products/socs/esp32-s3

I am planning on buying one of the boards mentioned on https://esp32s3.com; either the `FeatherS3` or `ProS3` as these seem to the only ones that have a JST connector.

Thanks,
\- Bana

**Comment by HaoboGu** [comment]
Yes, I do have plans to support esp32 series microcontrollers. I want to know a little more about your usage. Do you use esp32s3 with USB or only BLE?

**Comment by mbana** [comment]
I'd like to use both. Is there something that would limit me from doing so?

**Comment by HaoboGu** [comment]
Nothing, that's definitely possible. The only thing that could be limitation is my time. I'm writing this project in my spare time :D

**Comment by HaoboGu** [comment]
Hi! I just added esp32s3 support at https://github.com/HaoboGu/rmk/pull/35, but with BLE only for now. Would you like to have a simple test on it? I ordered a board but it takes some time.
