### ISSUE TITLE
Crash in ssmarshal upon press key

### ISSUE THREAD

**Issue by davidqge** [HaoboGu/rmk#57]
I changed esp32c3 to esp32c6. Had to increase stack size significantly in order to fix the crash before ble starts.
Now the BLE can connect, but crashes when press any key.

code is here: https://github.com/davidqge/rmk/tree/esp32c6_crash

`I (12564) NimBLE:  adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (12572) NimBLE:

thread 'main' panicked at /home/david-embedded/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ssmarshal-1.0.0/src/lib.rs:125:5:
8 <=? 4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

abort() was called at PC 0x4201de31 on core 0
0x4201de31 - panic_abort::__rust_start_panic::abort
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_abort/src/lib.rs:48
Core  0 register dump:
MEPC    : 0x408016c8  RA      : 0x4080b1da  SP      : 0x4081a920  GP      : 0x408113d0
0x408016c8 - panic_abort
    at /home/david-embedded/esp-idf-template/rmk/examples/use_rust/esp32c3_ble/.embuild/espressif/esp-idf/v5.1.3/components/esp_system/panic.c:472
0x4080b1da - __ubsan_include
    at /home/david-embedded/esp-idf-template/rmk/examples/use_rust/esp32c3_ble/.embuild/espressif/esp-idf/v5.1.3/components/esp_system/ubsan.c:313
0x408113d0 - __global_pointer$
    at ??:??
TP      : 0x407fcaa4  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x00000004  S1      : 0x4081a984  A0      : 0x4081a94c  A1      : 0x4081a982
A2      : 0x00000000  A3      : 0x4081a979  A4      : 0x00000001  A5      : 0x40814000
0x40814000 - tick_cb
    at ??:??
A6      : 0x00000000  A7      : 0x76757473  S2      : 0x00000001  S3      : 0x00000000
S4      : 0x408226e8  S5      : 0x00000000  S6      : 0x07000000  S7      : 0x00000000
S8      : 0x40820760  S9      : 0x408226f0  S10     : 0x4081bbac  S11     : 0x4081d5b8
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
0x40800001 - _vector_table
    at ??:??
MHARTID : 0x00000000

Stack memory:
4081a920: 0x00000002 0x00000000 0x4081a980 0x4080f944 0x4081a9a4 0x4087ccf0 0x00000000 0x408124d8
0x4080f944 - abort
    at /home/david-embedded/esp-idf-template/rmk/examples/use_rust/esp32c3_ble/.embuild/espressif/esp-idf/v5.1.3/components/newlib/abort.c:35
4081a940: 0x4081a984 0x408124f4 0x4081a980 0x726f6261 0x20292874 0x20736177 0x6c6c6163 0x61206465
4081a960: 0x43502074 0x34783020 0x64313032 0x20313365 0x63206e6f 0x2065726f 0x00000030 0x40830000
4081a980: 0x00000030 0x31303234 0x31336564 0x00000000 0x4081a988 0x408132c8 0x42099970 0x4201de34
0x408132c8 - std::io::stdio::STDOUT
    at ??:??
0x42099970 - $d
    at ??:??
0x4201de34 - <core::iter::sources::from_fn::FromFn<F> as core::iter::traits::iterator::Iterator>::next
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/sources/from_fn.rs:68
4081a9a0: 0x00000000 0x00000000 0x00000005 0x42015d22 0x00000008 0x4083b098 0x00000007 0x00000008
0x42015d22 - std::sys::thread_local::key::unix::get
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/thread_local/key/unix.rs:21
4081a9c0: 0x4083b098 0x00000007 0x408226e8 0x00000000 0x00000001 0x408132c8 0x42099970 0x4201c098
0x408132c8 - std::io::stdio::STDOUT
    at ??:??
0x42099970 - $d
    at ??:??
0x4201c098 - core::fmt::Arguments::new_const
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:339
4081a9e0: 0x00c61267 0x00000000 0x4083002c 0x4081aa70 0x420a6fac 0x42099970 0x4083002c 0x40802eb4
0x420a6fac - $d
    at ??:??
0x42099970 - $d
    at ??:??
0x40802eb4 - esp_timer_start_once
    at /home/david-embedded/esp-idf-template/rmk/examples/use_rust/esp32c3_ble/.embuild/espressif/esp-idf/v5.1.3/components/esp_timer/src/esp_timer.c:229
4081aa00: 0x00c61252 0x4082751c 0x00000001 0x00c6125d 0x00c61264 0x00000000 0x00000000 0x4201427e
0x4201427e - core::result::Result<T,E>::unwrap
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1100
4081aa20: 0x00c61252 0x4081aa70 0x420a6f70 0x42099970 0x42010001 0x00000000 0x4087ce84 0x4081d5b8
0x420a6f70 - $d
    at ??:??
0x42099970 - $d
    at ??:??
0x42010001 - alloc::vec::Vec<T,A>::append_elements
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2159
4081aa40: 0x4081bbac 0x408226f0 0x40820760 0x00000000 0x07000000 0x00000000 0x408226e8 0x4082078c
4081aa60: 0x4082049c 0x40812d60 0x00000000 0x4201bc22 0x00000008 0x4083b098 0x00000007 0x4081aa80
0x4201bc22 - std::panicking::payload_as_str
    at /home/david-embedded/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:744
4081aa80: 0x42099960 0x00000002 0x4081d5b8 0x00000002 0x00000000 0x00000008 0x42099970 0x4081aaa0
0x42099960 - $d
    at ??:??
0x42099970 - $d
    at ??:??
4081aaa0: 0x42099960 0x00000002 0x4081d5b8 0x00000002 0x00000000 0x00000008 0x42099970 0x42000001
0x42099960 - $d
    at ??:??
0x42099970 - $d
    at ??:??
4081aac0: 0xa5a5a5a5 0x408204a0 0x4081e23f 0x4081e960 0x4082050c 0x40820510 0x40820514 0x4081da40
4081aae0: 0x40820594 0x40820564 0x40820508 0x408226f0 0x00c6125b 0x00000000 0xa5a5a500 0xa5a5a5a5
4081ab00: 0x00c61264 0x00000000 0xa5a5a500 0xa5a5a5a5 0x00c61224 0x00000000 0xa5a5a500 0xa5a5a5a5
4081ab20: 0x00c6124f 0x00000000 0xa5a5a500 0xa5a5a5a5 0x00b6ceab 0x00000000 0xa5a5a500 0xa5a5a5a5
4081ab40: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ab60: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ab80: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081aba0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081abc0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081abe0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ac00: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ac20: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ac40: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ac60: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ac80: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081aca0: 0x00000002 0x0000001e 0x00020000 0x001f0000 0x00000000 0x00000002 0x00000020 0x00020000
4081acc0: 0x00210000 0x00000000 0x00000002 0x00000022 0x00020000 0x00230000 0x00000000 0x00000000
4081ace0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081ad00: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000002 0x0000002b

`

**Comment by HaoboGu** [comment]
Thanks for reporting it. Could you provide full backtrace by enabling RUST_BACKTRACE=1?

**Comment by davidqge** [comment]
Changed write_serialize to write fixed the problem.
Created a pull request along with several other fixes to make it work on esp32c6.
