### ISSUE TITLE
Community discussion

### ISSUE THREAD

**Issue by dzervas** [HaoboGu/rmk#68]
Heyo! Amazing what you've achieved - I've been trying to do the same in https://github.com/dzervas/pubsubinator which doesn't seem to make sense anymore

Is there some kind of community chat/forum? Most projects use discord and I like it a lot

**Comment by HaoboGu** [comment]
hello!
I have a discord channel(but very few people joined). 

https://discord.gg/6YF5qsYk

**Comment by HaoboGu** [comment]
btw your project seems not public available

**Comment by dzervas** [comment]
just made it public :)
