### ISSUE TITLE
BLE support for nRF52832

### ISSUE THREAD

**Issue by lonesometraveler** [HaoboGu/rmk#7]
Thank you for developing and maintaining this incredible project.

I've noticed that the BLE support is currently limited to nRF52840. Are there any plans to include support for nRF52832? If not, I'm willing to take on the task of adding support for nRF52832. I believe this will broaden the project's accessibility.

**Comment by HaoboGu** [comment]
Yeah, supporting other chips of nRF is on the future list, but I don't have a board for nRF52832/nRF52810/etc. It would be great if you could do this :D

**Comment by lonesometraveler** [comment]
Great. I have nRF52832 boards. I will work on it.

**Comment by HaoboGu** [comment]
I just made a minor modification of feature gates, end users would add only `nrf528xx_ble` feature, and `ble` feature will be added then.

**Comment by HaoboGu** [comment]
Could you please update [rmk-template](https://github.com/HaoboGu/rmk-template) as well, making nRF52832 ble feature available for more users?

**Comment by lonesometraveler** [comment]
I am not familiar with `cargo-generate`. But I'm open to learning and giving it a try.

**Comment by HaoboGu** [comment]
thanks!

**Comment by LXF-YZP** [comment]
> I just made a minor modification of feature gates, end users would add only 我只是对功能门进行了小幅修改，最终用户只会添加`nrf528xx_ble`feature, and feature，以及`ble`feature will be added then. 然后将添加功能。



> Could you please update [rmk-template](https://github.com/HaoboGu/rmk-template) as well, making nRF52832 ble feature available for more users?

Hello, can 52840 be edited online in vial? Whether it's wired or wireless?

**Comment by HaoboGu** [comment]
@LXF-YZP can only wired version of 52840 use vial for now. I'm doing a storage refactoring, which makes it possible to switch between usb/ble, then you can use vial after switching to usb mode. 

I also planned to test whether vial could be used in wireless mode, I don't know whether it's possible. PRs welcome!

**Comment by HaoboGu** [comment]
nRF52832 is now supported, closing this
