### ISSUE TITLE
`cargo build --release --bin peripheral` does not output hex file

### ISSUE THREAD

**Issue by akarsh1995** [HaoboGu/rmk#94]
When I initially downloaded rmk and tried an example it generated hex files and converted to uf2 as well.

I'm not sure what went wrong that `cargo build --release --bin peripheral` stopped generating hex file.

[Asciinema Recording](https://asciinema.org/a/wng0OPcik4EWYHN4sqUtF27mh)

Following is the modification diff
[corne-build-rmk.patch](https://github.com/user-attachments/files/17355967/corne-build-rmk.patch)

### Cargo version:
`cargo 1.81.0 (2dbb1af80 2024-08-20)`

### Rustc version:
`rustc 1.81.0 (eeb90cda1 2024-09-04)`

  
### Last rmk commit:

```commit c72bcd353f1cd462043c87e3db921f1dd0ef51b2 (HEAD -> main, origin/main, origin/HEAD)
Merge: caf5b82 5c719a9
Author: HaoboGu <haobogu@outlook.com>
Date:   Fri Oct 11 16:20:58 2024 +0800

    Merge pull request #93 from decaday/fix/matrix_row2col_col_value

    fix: Matrix row2col COL‘s value
```

**Comment by akarsh1995** [comment]
My terminal alacritty had an I/O issue. 
When I tried with macos stock terminal binaries output as expected.

**Comment by HaoboGu** [comment]
Hi！cargo build won't generate hex file. If you want to generate uf2, you can follow the instruction here: https://haobogu.github.io/rmk/user_guide/4_compile_and_flash.html#use-uf2-bootloader

**Comment by HaoboGu** [comment]
If you want hex only, you should use cargo objcopy, which requires cargo-binutil.

**Comment by akarsh1995** [comment]
This command `cargo build --release --bin central` outputs bin right?

**Comment by HaoboGu** [comment]
> This command `cargo build --release --bin central` outputs bin right?

it generates ELF file actually

**Comment by akarsh1995** [comment]
> > This command `cargo build --release --bin central` outputs bin right?
> 
> it generates ELF file actually





I again, cannot locate elf/bin after running the command `cargo build --release --bin central` in the `examples/use_rust/nrf52840_ble_split`.

### The build process just finishes like so

```
   Compiling embassy-nrf v0.2.0 (/Users/akarshjain/temp/embassy/embassy-nrf)
    Finished `release` profile [optimized + debuginfo] target(s) in 21.00s
```


Am I missing something?

**Comment by HaoboGu** [comment]
> 
> 
> > > This command `cargo build --release --bin central` outputs bin right?
> 
> > 
> 
> > it generates ELF file actually
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> I again, cannot locate elf/bin after running the command `cargo build --release --bin central` in the `examples/use_rust/nrf52840_ble_split`.
> 
> 
> 
> ### The build process just finishes like so
> 
> 
> 
> ```
> 
>    Compiling embassy-nrf v0.2.0 (/Users/akarshjain/temp/embassy/embassy-nrf)
> 
>     Finished `release` profile [optimized + debuginfo] target(s) in 21.00s
> 
> ```
> 
> 
> 
> 
> 
> Am I missing something?
> 
> 
> 
> 
> 
> 

the generated ELF is at target/<ARCH>/release. The ELF filename is the bin name set in Cargo.toml, with no extension

**Comment by akarsh1995** [comment]
> > 
> > 
> > > > This command `cargo build --release --bin central` outputs bin right?
> > 
> > > 
> > 
> > > it generates ELF file actually
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > 
> > I again, cannot locate elf/bin after running the command `cargo build --release --bin central` in the `examples/use_rust/nrf52840_ble_split`.
> > 
> > 
> > 
> > ### The build process just finishes like so
> > 
> > 
> > 
> > ```
> > 
> >    Compiling embassy-nrf v0.2.0 (/Users/akarshjain/temp/embassy/embassy-nrf)
> > 
> >     Finished `release` profile [optimized + debuginfo] target(s) in 21.00s
> > 
> > ```
> > 
> > 
> > 
> > 
> > 
> > Am I missing something?
> > 
> > 
> > 
> > 
> > 
> > 
> 
> the generated ELF is at target/YOUR_ARCH/release. The ELF filename is the bin name set in Cargo.toml, with no extension 

Sorry for the noob question but

how do I convert elf to uf2 so that I could flash it via bootloader in my nrf52840?

**Comment by HaoboGu** [comment]
ahh, doesn't `cargo make uf2 --release` work?

**Comment by HaoboGu** [comment]
It seems that python is not installed at your machine. can you try `python --version` command?

**Comment by akarsh1995** [comment]
<img width="890" alt="image" src="https://github.com/user-attachments/assets/f7903e29-e6c1-4514-a159-e4d58b6c141a">


python isn't there python3 is

I'll soft link it to python

**Comment by HaoboGu** [comment]
You can also change `python` in `Makefile.toml` to use `python3`. I think I'd add more documents about this..
