### ISSUE TITLE
Create a Discord Channel for RMK Community Development

### ISSUE THREAD

**Issue by akarsh1995** [HaoboGu/rmk#98]
RMK has the potential to stand out as a strong alternative to both ZMK and QMK. While ZMK and QMK enjoy substantial community support, I believe there is an opportunity to setup a community around RMK as well.

To support this initiative, I propose creating a dedicated Discord channel where RMK users, developers, and enthusiasts can collaborate, share knowledge, and contribute to the development of RMK.

This channel would help engage the community, provide a space for discussions, and encourage new contributors to get involved, thereby strengthening the RMK ecosystem.

**Comment by HaoboGu** [comment]
I do have a discord channel and I put a badge for discord in readme.. But only a few people joined🥲

**Comment by akarsh1995** [comment]
Apart from the badge can you also add the hyperlink in the Readme. That way it's easier to search. I searched for the term discord but couldn't find it. I totally missed the badge at the top.

You get the sense


<img width="1212" alt="image" src="https://github.com/user-attachments/assets/936bd8f1-91b9-4870-a9be-8382cb328cd2">
